version: '3.4'

services:
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: Auth.Api/Dockerfile
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
  logs.api:
    image: logs.api
    build:
      context: .
      dockerfile: Logs.Api/Dockerfile